import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * The rules every workspace shares.
 *
 * Deliberately close to the recommended sets rather than an opinionated
 * superset. This repository's backend had never been linted at all, so the
 * starting point was chosen by measuring what the code already satisfies —
 * see docs/adr/0005-shared-lint-config.md. Tightening is issue #30.
 *
 * `eslint-config-prettier` comes last so that formatting rules stay off:
 * Prettier owns formatting here, and two tools arguing about it is worse than
 * either one deciding.
 */
export const base = [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/.strapi/**',
      // Strapi's own scratch directory, holding the SQLite database and whatever
      // throwaway scripts you point at it. Git ignores it; lint should too, or a
      // one-off script breaks the gate.
      '**/.tmp/**',
      '**/coverage/**',
      // Generated by Strapi and mirrored into @repo/strapi-types. Linting
      // generated output reports problems nobody can fix at the source.
      '**/types/generated/**',
      'packages/strapi-types/generated/**',
      // Scaffolding templates that Strapi ships for developers to copy. They
      // are never imported or built, so holding them to the same rules as live
      // code reports problems that cannot meaningfully be fixed.
      '**/*.example.*',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node, ...globals.es2021 },
    },
    rules: {
      // The repo's own standard, from AGENTS.md: prefer unknown over any, and
      // tighten existing broad types incrementally. Promoted from warning to
      // error in #30, once #15 had converted the frontend and taken the count
      // from 73 to 0. Four `any`s remain, each disabled in place with a stated
      // reason where no non-any type exists: the dynamic-zone dispatcher, the
      // polymorphic Button element, react-three-fiber's invariant mesh ref, and
      // tsparticles' v2 boolean shorthand.
      '@typescript-eslint/no-explicit-any': 'error',

      // Unused variables are a genuine signal, but an underscore prefix is the
      // conventional way to say "deliberately unused" for required positional
      // arguments and destructured rest siblings.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  {
    // Config and script files run in Node and are not part of either app's
    // build output, so they get Node globals.
    //
    // `require()` is allowed here specifically, and only here. Tailwind's
    // config resolves plugins with require() by convention, and Strapi's
    // scripts/ are plain CommonJS invoked by `node` rather than bundled — in
    // both cases the import style is imposed by the tool, not chosen.
    files: [
      '**/*.config.{js,cjs,mjs,ts,mts}',
      '**/scripts/**/*.{js,cjs,mjs,ts,mts}',
    ],
    languageOptions: { globals: globals.node },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  prettier,
];

export default base;
